# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 853291b9458d53f7bd25e841f5a5fa076f85c1a81dd247e802f7a3b4ddf7ccb79d8701ff6372574d284993de2f753a65ed17f6cba61e6fe4c3dc48e747ed7809

test:
  secret_key_base: 0fe7bdce1b9f92be14eb4569912d925f49e8883f48785271c519bf13429b8524ea034fdebfd735e7ed496c6249cc5cb34c3ac8b92e8b634aca12c010df90b8b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
